.TH DECLAN 1 "July 2026" "Declan" "User Commands"



.SH NAME
Declan \- Declarative Arch Linux system management tool.



.SH SYNOPSIS
.B declan
.IR < operation > " [option]"



.SH DESCRIPTION
.B Declan
is a utility for declarative management of Arch and Arch-based Linux.
.br
It has options purposefully akin to some of NixOS's.
.br
However, it merely consumes a static, non-programmable file and executes simple operations.



.SH CONFIGURATION
Declan consumes a JSON file (stored in ~/) which records the user's configuration preferences:

.nf
{
    "description": "<user>'s <distro> configuration",

    "packages": [
    ],

    "services": [
    ],

    "gc": {
        "enabled": true,
        "include": [
            "~/*"
        ]
    },

    "rice": {
        "enabled": false,
        "remote": "user/repo",
        "include": [
            "app/"
        ]
    },

    "backup": {
        "enabled": true,
        "path": "~/file.tar.xz",
        "include": [
            "~/"
        ]
    }
}
.fi

The file structure on display herein is mandatory.
.br
Options themselves, however, may vary, as the user is expected to choose a feature set to accomodate their needs.



.SH OPERATIONS
Declared configurations are applied and/or executed on demand through various operations: 

.TP
.BR 'init'
Initializes Declan through a series of command-line prompts [...]

.TP
.BR 'clear'
Remove Declan's stored data from the system.

.TP
.BR 'relay'
Install newly added packages and remove delisted ones.

.TP
.BR 'rebuild'
Perform a system upgrade.

.TP
.BR 'gc'/garbage-collect
Remove listed files and directories.

.TP
.BR 'rice'
Upload select configuration files to a remote.

.TP
.BR 'backup'
Back up listed files to an archive. Uses xz.



.SH OPTIONS
.TP
.BR -h ", " --help
Display command-line usage information.

.TP
.BR -v ", " --version
Display the program's logo, current version, and license terms.

.TP
.B --gc
Perform garbage collection during
.B rebuild.

.TP
.B --casc
Iteratively attempt cascading removal of packages set for uninstallation.



.SH EXAMPLES
.nf
declan init
declan -v
declan rebuild --gc --casc
declan --help
.fi
