.TH DECLAN 1 "June 2026" "Declan" "User Commands"

.SH NAME
Declan \- Declarative system configuration tool for Arch and Arch based Linux distributions.

.SH SYNOPSIS
.B declan
.IR < operation > " [option]"

.SH DESCRIPTION
Manage packages, cleanups, configuration files, and backups.

.SS File format
"packages"
.br
list of packages to remain installed and updated
.br
.IR NOTE(!):
Not necessarily exhaustive; required dependencies not specified.

"services"
list of packages keep enabled

"gc": {
    "enabled": true/false,
    "clean": []
},

"configs": {
    "enabled": true/false,
    "include": []
},

"backup": {
    "enabled": true/false,
    "include": []
}
}
