
"""
Declan

A tiny declarative system specification tool
for Arch-based Linux systems

https://github.com/monikrab/declan
"""


import json

from subprocess import run
from argparse import ArgumentParser
from pathlib import Path
from getpass import getuser
from sys import exit
from textwrap import dedent
from os import environ as env, getenv
from pprint import pprint
from shutil import copy as copy, which as which



# Error classes
class DeclanError(Exception):
    pass

class EnvVarExistsError(DeclanError):
    def __init__(self, path):
        super().__init__(
            f"\033[91m error:\033[0m environment variable already defined in ~/{path}"
        )



# Supported operations:
# init, relay (partial), rebuild (partial)
parser = ArgumentParser()

parser.add_argument(
    "operation",
    nargs="?",
    choices = ["init", "relay", "rebuild"]
)

parser.add_argument(
    "clean",
    nargs="?",
    choices = ["noclean"]
)

args = parser.parse_args()




# Check which Arch(-based) distribution is in use
release = Path("/etc/os-release").read_text()

if   "ID=cachyos" in release:     distro = "CachyOS"
elif "ID=arch" in release:        distro = "Arch Linux"
elif "ID=manjaro" in release:     distro = "Manjaro"
elif "ID=endeavouros" in release: distro = "EndeavourOS"



def init():
    # Welcome message
    print(
        """
  _____    _______   _____   _                 _   _ 
 |  __ \\  |  ____/  / ____\\ | |         Λ     | \\ | |
 | |  | | | |___   | /      | |        / \\    |  \\| |
 | |  | | |  ___|  | |      | |       / △ \\   |     |
 | |__| | | |____  | \\____  | |___   / ___ \\  | |\\  |
 |_____/  \\______\\  \\_____/ \\_____/ /_/   \\_\\ |_| \\_|
        \033[3mdeclarative system configuration for 󰣇\033[0m""",
    end="\n\n"
    )


    # Name the file
    config_name = ""
    while not config_name.strip():
        config_name = str(input("\n Enter the name for your configuration file.\n"
                                " Do not add a file extension.\n\n"
                                " Name: "))
    username = getuser()
    config_path = Path(f"/home/{username}/{config_name}.json")


    # Create the file if it doesn't exist
    try:
        with open(config_path, "x") as f:
            f.write(f"""{{
    "description": "{username}'s {distro} configuration",

    "packages": [],
    
    "services": [],

    "gc": {{
        "enabled": false,
        "clean": []
    }},

    "configs": {{
        "enabled": false,
        "include": []
    }},

    "backup": {{
        "enabled": false,
        "include": []
    }}
}}
""")
    except FileExistsError:
        print("\033[91m error:\033[0m configuration file already exists at", config_path)
        exit(1)
    else:
        print("\n\033[92m Config file created.\n \033[0mPath to config:", config_path, end="\n\n")
    

    # Add an environment variable to the login shell's config
    env_var_confirm = ""
    while env_var_confirm.lower() not in ["y", "n"]:
        env_var_confirm = str(input(" Add path to a permanent environment variable? [Y/n]: "))

    if env_var_confirm == "y":
        user_sh = env.get("SHELL")

        env_var = dedent(f"""
            # Automatically generated by `declan init`
            export DECLAN_CONFIG_PATH='{config_path}'"""
        )


        if   user_sh in ["/usr/bin/fish", "/bin/fish"]: path = ".config/fish/config.fish" 
        elif user_sh in ["/usr/bin/zsh", "/bin/zsh"]:   path = ".zshrc"
        elif user_sh in ["/usr/bin/bash", "/bin/bash"]: path = ".bashrc"
        
        with open(f"/home/{username}/{path}", "a+") as f:
            f.seek(0)
            if "DECLAN_CONFIG_PATH" in f.read(): raise EnvVarExistsError(path)
            else:
                f.write(env_var)
                print("\n\033[92m Environment variable set.\033[0m", end="\n")


    return config_path



def parse(path):
    with open(path, "r") as f:
        declan = json.load(f)


    """
    Codes:
        P -> Packages
        S -> Services
        C -> Configs
        B -> Backup
    """

    enabled_features = ""
    values = [None]; values[0]

    if declan["packages"]:
        enabled_features += "P"
        packages = declan["packages"]; values.append(packages)

    if declan["services"]:
        enabled_features += "S"
        services = declan["services"]; values.append(services)

    if declan["gc"]["enabled"]:
        enabled_features += "G"
        clean = declan["gc"]["clean"]; values.append(clean)

    if declan["configs"]["enabled"]:
        enabled_features += "C"
        configs = declan["configs"]; values.append(configs)

    if declan["backup"]["enabled"]:
        enabled_features += "B"
        backup = declan["backup"]; values.append(backup)

    values[0] = enabled_features
    return values



def relay(pkgs, services):
    # TODO: Add caching to detect which packages are new at list time
    if pkgs != None:
        print("\033[1mPackages to install:\033[0m\n\n", '\n'.join(pkgs), sep="", end="\n\n")
    if services != None:
        print("Services to enable:\n\n", '\n'.join(services), sep="", end="\n\n")
    if services and packages == None:
        print("There is nothing to do")


    if str(input(":: Proceed? [Y/n]: ")).lower() == "y":
        print()
        run(["sudo", "-v"])
        run(
            ["yay", "-S", "--noconfirm", "--noprogressbar", "--needed", *pkgs],
            text=True
        )



def rebuild(pkgs, services):
    if pkgs != None:
        print("\033[1mPackages to upgrade:\033[0m\n\n", '\n'.join(pkgs), sep="", end="\n\n")
    if services != None:
        print("Services to enable:\n\n", '\n'.join(services), sep="", end="\n\n")
    if services and packages == None:
        print("There is nothing to do")


    if str(input(":: Proceed? [Y/n]: ")).lower() == "y":
        print()
        run(["sudo", "-v"])
        run(
            ["yay", "-Syu", "--noconfirm", "--noprogressbar", *pkgs],
            text=True
        )



# def garbage_collect():



# def rice():
# --push



# def backup():



# def clear():



def main():
    if args.operation == "init": config_path = init()
    else: config_path = getenv("DECLAN_CONFIG_PATH")

    features = parse(config_path)

    def check_yay():
        if which("yay") is None:
            install_yay = str(input("\033[91m error:\033[0m yay (AUR helper) is not installed\n\n"
                                    " Without it, the following operations are unavailable:\n"
                                    " relay, rebuild\n\n"
                                    " Would you like to install it now? [Y/n]: "))

        if install_yay.lower() == "y":
            print("TODO")
        else:
            exit(1)
        

    if args.operation == "relay":
        check_yay()
        if "P" in features[0] or "S" in features[0]:
            if "S" not in features[0]:
                relay(features[1], None)
            elif "P" not in features[0]:
                relay(None, features[2])
            else:
                relay(features[1], features[2])
                
    # if args.operation == "rebuild":
        # check_yay()
        # if "P" in features[0] or "S" in features[0]:
        #     if "S" not in features[0]:
        #         relay(features[1], None)
        #     elif "P" not in features[0]:
        #         relay(None, features[2])
        #     else:
        #         relay(features[1], features[2])


try:
    main()
except DeclanError:
    print(DeclanError)
    exit(1)
except (KeyboardInterrupt, EOFError):
    print("\n\n\033[91m error:\033[0m execution interrupted by user!")
