
"""
Declan

A tiny declarative system specification tool
for Arch-based Linux systems

https://github.com/monikrab/declan
"""


import json

from subprocess import run, DEVNULL, PIPE
from argparse import ArgumentParser
from pathlib import Path
from getpass import getuser
from sys import exit
from textwrap import dedent
from shutil import copy2, which
from os import environ as env, getenv



# Error classes
class DeclanError(Exception):
    pass

class EnvVarExistsError(DeclanError):
    def __init__(self, path):
        super().__init__(
            f"\033[91m error:\033[0m environment variable already defined in ~/{path}"
        )



# Supported operations:
# init, relay (partial), rebuild (partial)
parser = ArgumentParser()

parser.add_argument(
    "operation",
    nargs="?", # TODO: add usage when no flags passed
    choices = ["init", "relay", "rebuild"]
)

parser.add_argument(
    "clean",
    nargs="?",
    choices = ["noclean"]
)

args = parser.parse_args()




# Check which Arch(-based) distribution is in use
release = Path("/etc/os-release").read_text()

if   "ID=cachyos" in release:     distro = "CachyOS"
elif "ID=arch" in release:        distro = "Arch Linux"
elif "ID=manjaro" in release:     distro = "Manjaro"
elif "ID=endeavouros" in release: distro = "EndeavourOS"



def init():
    # Welcome message
    print(
        """
  _____    _______   _____   _          _      _   _
 |  __ \\  |  ____/  / ____\\ | |        / \\    | \\ | |
 | |  | | | |___   | /      | |       /   \\   |  \\| |
 | |  | | |  ___|  | |      | |      /  ∆  \\  |     |
 | |__| | | |____  | \\____  | |___  /  ___  \\ | |\\  |
 |_____/  \\______\\  \\_____/ \\_____/ \\_/   \\_/ |_| \\_|
        \033[3mdeclarative system configuration for 󰣇\033[0m""",
    end="\n\n"
    )


    # Name the file
    config_name = ""
    while not config_name.strip(): # remove whitespace
        config_name = str(input("\n Enter the name for your configuration file.\n"
                                " Do not add a file extension.\n\n"
                                " Name: "))
    username = getuser()
    config_path = Path(f"/home/{username}/{config_name}.json")


    # Create the file if it doesn't exist
    try:
        with open(config_path, "x") as f:
            f.write(f"""{{
    "description": "{username}'s {distro} configuration",

    "packages": [],
    
    "services": [],

    "gc": {{
        "enabled": false,
        "clean": []
    }},

    "configs": {{
        "enabled": false,
        "include": []
    }},

    "backup": {{
        "enabled": false,
        "include": []
    }}
}}
""")
    except FileExistsError:
        print("\033[91m error:\033[0m configuration file already exists at", config_path)
        exit(1)
    else:
        print("\n\033[92m Config file created.\n \033[0mPath to config:", config_path, end="\n\n")
    

    # Add an environment variable to the login shell's config
    env_var_confirm = ""
    while env_var_confirm.lower() not in ["y", "n"]:
        env_var_confirm = str(input(" Add path to a permanent environment variable? [Y/n]: "))

    if env_var_confirm == "y":
        user_sh = env.get("SHELL")

        env_var = dedent(f"""
            # Automatically generated by `declan init`
            export DECLAN_CONFIG_PATH='{config_path}'"""
        )


        if   user_sh in ["/usr/bin/fish", "/bin/fish"]: path = ".config/fish/config.fish" 
        elif user_sh in ["/usr/bin/zsh", "/bin/zsh"]:   path = ".zshrc"
        elif user_sh in ["/usr/bin/bash", "/bin/bash"]: path = ".bashrc"
        
        with open(f"/home/{username}/{path}", "a+") as f:
            f.seek(0)
            if "DECLAN_CONFIG_PATH" in f.read(): raise EnvVarExistsError(path)
            else:
                f.write(env_var)
                print("\n\033[92m Environment variable set.\033[0m", end="\n")


    return config_path



def parse_config(path):
    with open(path, "r") as f:
        declan = json.load(f)


    """
    Codes:
        P -> Packages
        S -> Services
        C -> Configs
        B -> Backup
    """

    enabled_features = ""
    values = [None]; values[0]

    if declan["packages"]:
        enabled_features += "P"
        packages = declan["packages"]; values.append(packages)

    if declan["services"]:
        enabled_features += "S"
        services = declan["services"]; values.append(services)

    if declan["gc"]["enabled"]:
        enabled_features += "G"
        clean = declan["gc"]["clean"]; values.append(clean)

    if declan["configs"]["enabled"]:
        enabled_features += "C"
        configs = declan["configs"]; values.append(configs)

    if declan["backup"]["enabled"]:
        enabled_features += "B"
        backup = declan["backup"]; values.append(backup)

    values[0] = enabled_features
    return values



# TODO: Add caching to detect which packages are new at list time
def relay_rebuild(packages, services, cache_path):
    if services is None and packages is None:
        print("There is nothing to do")
        return

    print()
    if args.operation == "relay":
        if packages is not None:
            print("\033[1mPackages to install:\033[0m\n", '\n'.join(packages), sep="", end="\n\n")

    elif args.operation == "rebuild":
        print("\033[1mPackages to update:\033[0m")

        pending_updates = run(
            ["pacman", "-Quq"], stdout=PIPE
        )
        run(
            ["column", "-S", "2"],
            input=pending_updates.stdout
        )
        print()
        
    if services is not None:
        print("\033[1mServices to enable:\033[0m\n", '\n'.join(services), sep="", end="\n\n")


    while 1:
        proceed = str(input("\033[35m::\033[0m Proceed? [Y/n]: ")).strip().lower(); print()
        if proceed in ["y", "n"]:
            if proceed == "n": return
            break


    run(["sudo", "-v"])

    if packages is not None:
        if args.operation == "relay":
            run(
                ["yay", "-S", "--asexplicit",
                "--noconfirm", "--noprogressbar", "--needed", *packages],
            )
        elif args.operation == "rebuild":        
            run(
                ["yay", "-Syu", "--noconfirm", "--noprogressbar", *packages],
            )
        
    if services is not None:
        print("\nEnabling services...", end="\n")
        run(
            ["sudo", "systemctl", "enable", "--now", *services],
        )
        print("Done.")
        


def cache_config(home_path, user):
    # Keep cached configs in .cache/declan
    cache_path = Path(f"/home/{user}/.cache/declan")
    cache_path.mkdir(exist_ok=True)

    copy2(home_path, cache_path)

    # TODO: Rename cached file to {edit_timestamp}.json
    # cache_filepath = cache_path + ""



# def garbage_collect():



# def rice():
# --push



# def backup():



# def clear():



def main():
    if args.operation == "init": config_path = init()
    else:
        config_path = getenv("DECLAN_CONFIG_PATH")
        username = getuser()

    features = parse_config(config_path)


    def check_yay():
        if which("yay") is None:
            install_yay = str(input("\033[91m error:\033[0m yay (AUR helper) is not installed\n\n"
                                    " Without it, the following operations are unavailable:\n"
                                    " relay, rebuild\n\n"
                                    " Would you like to install it now? [Y/n]: "))
        else:
            return

        if install_yay.lower() == "y":
            print("TODO")
        else:
            exit(1)
        

    if args.operation in ["relay", "rebuild"]:
        check_yay()

        cache_path = f"/home/{username}/.cache/declan/" + config_path[config_path.rfind("/") + 1:]
        
        if "P" in features[0] or "S" in features[0]:
            if "S" not in features[0]:
                relay_rebuild(features[1], None, cache_path)
            elif "P" not in features[0]:
                relay_rebuild(None, features[1], cache_path)
            else:
                relay_rebuild(features[1], features[2], cache_path)

            cache_config(config_path, username)


try:
    main()

except DeclanError:
    print(DeclanError)
    exit(1)

except (KeyboardInterrupt, EOFError):
    print("\n\n\033[91m error:\033[0m execution interrupted by user!")
