
import json
from argparse import ArgumentParser
from pathlib import Path
from getpass import getuser
from sys import exit
from os import environ as env, getenv
from textwrap import dedent
from subprocess import run, DEVNULL, PIPE
from shutil import copy2, which
from datetime import datetime as dt



class DeclanError(Exception):
    pass

class EnvVarExistsError(DeclanError):
    def __init__(self, path):
        super().__init__(
            f"""\n\033[91m error:\033[0m environment variable already exists in {path}
 Make sure it matches your configuration file's path!"""
        )

# class ConfigAlreadyInit(DeclanError):
#     def __init__(self, path):
#         super().__init__(f"""\033[91merror:\033[0m config already initialized at {path}""")



parser = ArgumentParser(
    prog="declan",
    usage="declan <operation> [options]",
    add_help=False,
    color=False
)

parser.add_argument(
    "-h", "--help",
    action="store_true",
)

parser.add_argument(
    "-v", "--version",
    action="store_true",
)

parser.add_argument(
    "operation",
    nargs="?",
    choices = ["init", "clear", "relay", "rebuild", "gc", "rice", "backup"]
)

# TODO
# parser.add_argument(
#     "--gc",
#     nargs="?",
# )
# parser.add_argument(
#     "--casc",
#     nargs="?",
# )
# parser.add_argument(
#     "--push",
#     nargs="?",
# )

args = parser.parse_args()




user = getuser()
cache_path = Path(f"/home/{user}/.cache/declan")
cache_path.parent.mkdir(parents=True, exist_ok=True)




version = "\033[3mversion 1.0\033[0m"

usage = """usage: declan <operation> [options]\n
operations:
    declan {-h | --help}
    declan {-v | --version}
    declan init
    declan clear
    declan relay    [--gc] [--casc]
    declan rebuild  [--gc] [--casc]
    declan gc
    declan rice     [--push]
    declan backup"""


logo = """\033[1m  _____    _______   _____   _          _      _   _
 |  __ \\  |  ____/  / ____\\ | |        / \\    | \\ | |
 | |  | | | |___   | /      | |       /   \\   |  \\| |
 | |  | | |  ___|  | |      | |      /  ∆  \\  |     |
 | |__| | | |____  | \\____  | |___  /  ___  \\ | |\\  |
 |_____/  \\______\\  \\_____/ \\_____/ \\_/   \\_/ |_| \\_|\033[0m"""




def init():
    print("\n", logo,
          "\n       \033[3;90mdeclarative system configuration for 󰣇\033[0m",
          end="\n\n"
      )

    config_name = ""
    while not config_name.strip():
        config_name = str(input("\n Enter the name for your configuration file.\n"
                                " Do not add a file extension.\n\n"
                                " Name: "))
    config_path = Path(f"/home/{user}/{config_name}.json")


    release = Path("/etc/os-release").read_text()
    if   "ID=cachyos" in release:     distro = "CachyOS"
    elif "ID=arch" in release:        distro = "Arch Linux"
    elif "ID=manjaro" in release:     distro = "Manjaro"
    elif "ID=endeavouros" in release: distro = "EndeavourOS"
    elif "ID=omarchy" in release:     distro = "Omarchy"
    elif "ID=garuda" in release:      distro = "Garuda Linux"
    elif "ID=biglinux" in release:    distro = "BigLinux"
    elif "ID=artix" in release:       distro = "Artix Linux"
    elif "ID=archcraft" in release:   distro = "Archcraft"
    else:
        print("\033[91m error:\033[0m unsupported operating system")
        exit(1)


    default_config = json.dumps({
        "description": f"{user}'s {distro} configuration",
        "packages": [],
        "services": [],
        "gc": {
            "enabled": False,
            "clean": []
        },
        "configs": {
            "enabled": False,
            "include": []
        },
        "backup": {
            "enabled": False,
            "include": []
        }
    }, indent=4)

    try:
        with open(config_path, "x") as f:
            f.write(default_config)
    except FileExistsError:
        print("\033[93m warning:\033[0m file already exists! (", config_path, ")",
              "\n\n Trying to set config path environment variable...", sep="")
    else:
        print("\n\033[92m Config file created.\n \033[0mPath to config:", config_path, end="\n")

        with open(cache_path / "declan.log", "a") as log:
            print(dt.now(), ": Written config file to ", config_path, sep="", file=log)

        with open(cache_path / (dt.now().strftime('%Y-%m-%d_%H-%M') + ".json"), "w") as default_log:
            default_log.write(default_config)



    user_sh = env.get("SHELL")
    if   user_sh in ["/usr/bin/fish", "/bin/fish"]: sh_path = ".config/fish/config.fish" 
    elif user_sh in ["/usr/bin/zsh", "/bin/zsh"]:   sh_path = ".zshrc"
    elif user_sh in ["/usr/bin/bash", "/bin/bash"]: sh_path = ".bashrc"

    env_var = dedent(f"""
        # Automatically generated by `declan init`
        export DECLAN_CONFIG_PATH='{config_path}'"""
    )
    with open(f"/home/{user}/{sh_path}", "a+") as f:
        f.seek(0)
        if "DECLAN_CONFIG_PATH" in f.read(): raise EnvVarExistsError(sh_path)
        else:
            f.write(env_var)
            print(" \033[3m(saved at", sh_path, "as $DECLAN_CONFIG_PATH)\033[0m", end="\n")


    print("\033[92m\n Initialization finished.\033[0m\n"
          "\033[91m Please restart your shell before using Declan!\033[0m\n"
          " For usage instructions, type 'declan --h' or 'man 1 declan' into your shell\n\n"
          "\033[95m Enjoy :V\033[0m")        




def parse_config(path):
    with open(path, "r") as f:
        declan = json.load(f)

    """
    Codes:
        P -> Packages | [1]
        S -> Services | [2]
        G -> Garbage  | [3]
        C -> Configs  | [4]
        B -> Backup   | [5]
    """

    enabled_features = ""
    config_data = [None,  None, None, None, None, None]

    if declan["packages"]:
        enabled_features += "P"
        packages = declan["packages"]; config_data[1] = packages

    if declan["services"]:
        enabled_features += "S"
        services = declan["services"]; config_data[2] = services

    if declan["gc"]["enabled"]:
        enabled_features += "G"
        clean = declan["gc"]["clean"]; config_data[3] = clean

    if declan["configs"]["enabled"]:
        enabled_features += "C"
        configs = declan["configs"]["include"]; config_data[4] = configs

    if declan["backup"]["enabled"]:
        enabled_features += "B"
        backup = declan["backup"]["include"]; config_data[5] = backup

    config_data[0] = enabled_features
    return config_data




def cache_config(config_name, user):
    stats = home_path.stat()
    last_modification = dt.fromtimestamp(stats.st_mtime)
    date_l_m = last_modification.strftime("%Y-%m-%d_%H-%M")

    copy2(home_path, cache_path / (date_l_m + ".json") )




def relay_rebuild(packages, services):
    cache_path = next(
                      Path(f"/home/{user}/.cache/declan").glob("*.json"),
                      None
                  )
    with open(cache_path, "r") as cached:
        cached_config = json.load(cached)


    to_remove = None; to_disable = None

    if args.operation == "relay":
        if packages is not None:
            print("\033[1mPackages to install:\033[0m\n", '\n'.join(packages), sep="", end="\n\n")
            to_remove = list(set(cached_config["packages"]) - set(packages))            

    elif args.operation == "rebuild":
        print("\033[1mPackages to update:\033[0m")

        pending_updates = run(
            ["pacman", "-Quq"], stdout=PIPE
        )
        run(
            ["column", "-S", "2"], input=pending_updates.stdout
        )
        print()

    if to_remove:
        print("\033[1mPackages to remove:\033[0m\n", '\n'.join(to_remove), sep="", end="\n\n")

    
    if services is not None:
        print("\033[1mServices to enable:\033[0m\n", '\n'.join(services), sep="", end="\n\n")
        to_disable = list(set(cached_config["services"]) - set(services))
    if to_disable:
        print("\033[1mServices to disable:\033[0m\n", '\n'.join(to_disable), sep="", end="\n\n")


    while 1:
        proceed = str(input("\033[35m::\033[0m Proceed? [Y/n]: ")).strip().lower(); print()
        if proceed in ["y", "n"]:
            if proceed == "n": return
            break


    run(["sudo", "-v"])
    
    if packages is not None:
        if args.operation == "relay":
            run(
                ["yay", "-S", "--asexplicit",
                "--noconfirm", "--noprogressbar", "--needed", *packages],
            )
        elif args.operation == "rebuild":        
            run(
                ["yay", "-Syu", "--noconfirm", "--noprogressbar", *packages],
            )
    
    # if services is not None:
    #     print("\nEnabling services...", end="\n")
    #     run(
    #         ["sudo", "systemctl", "enable", "--now", *services],
    #     )
    #     print("Done.")




def main():
    if args.operation is None:
        if args.version is True:
            print(
                logo, " " + version,
                "\n This program may be freely redistributed under",
                " the terms of the GNU General Public License, version 2.0",
                sep="\n", end="\n\n"
             )
            exit(0)

        if args.help is True: print(usage)
        # if args.gc is True:
        # print("\033[91merror:\033[0m option 'gc' can only be used with operations:\n"
        #       "relay\nrebuild\n",
        #       usage)
        else: print(usage)
    
    
    if args.operation == "init":
        init()
        # try:
        #     with open(f"/home/{user}/.cache/declan/declan.log", "r") as log:
        #         file = log.read()
        #         if "Written config file to" in file:
        #             raise ConfigAlreadyInit(getenv("DECLAN_CONFIG_PATH"))
        # except FileNotFoundError:
        #     init()
        #     exit(0)


    config_path = Path(getenv("DECLAN_CONFIG_PATH"))
    # add failure case(s) here
    features = parse_config(config_path)



    if args.operation in ["relay", "rebuild"]:
        if which("yay") is None:
            install_yay = str(input("\033[91m error:\033[0m yay (AUR helper) is not installed\n\n"
                                    " Without it, the following operations are unavailable:\n"
                                    " relay, rebuild\n\n"
                                    " Would you like to install it now? [Y/n]: "))
            
            if install_yay.lower() == "y":
                run("yay -Y --gendb && yay -Y --devel --save", shell=True)
                run("sudo pacman -S --needed git base-devel", shell=True)
                run("git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si",
                    shell=True)
            else:
                exit(1)

        
        if "P" in features[0] or "S" in features[0]:
            if "S" not in features[0]:
                relay_rebuild(features[1], None)
            elif "P" not in features[0]:
                relay_rebuild(None, features[2])
            else:
                relay_rebuild(features[1], features[2])
        else:
            print("there is nothing to do")
            return



try:
    main()
except DeclanError as error:
    print(error)
except (KeyboardInterrupt, EOFError):
    print("\n\n\033[91m error:\033[0m execution interrupted by user!")
